export const featuredProjects = [
  {
    id: "business-dashboard",
    projectTitle: "Business Dashboard",
    subTitle: "Comprehensive sales dashboard for insightful business analytics and performance optimization. Real-time data visualization with interactive charts.",
    imgPath: "./Projects images/Next.js/dashboard.png",
    liveDemo: "https://business-sales-dashboard.vercel.app/",
    github: "https://github.com/aymantarek16/business-sales-dashboard",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Chart.js"],
    category: "Analytics",
  },
  {
    id: "virtix-studio",
    projectTitle: "Virtix Studio",
    subTitle: "Premium digital design agency website designed to showcase creative work with stunning animations and modern UX.",
    imgPath: "./Projects images/Next.js/virtix.png",
    liveDemo: "https://virtix-studio.vercel.app/",
    github: "https://github.com/aymantarek16/virtix-studio",
    techStack: ["Next.js", "Framer Motion", "GSAP", "Tailwind"],
    category: "Agency",
  },
  {
    id: "schedule-app",
    projectTitle: "Schedule App",
    subTitle: "Modern appointment scheduling app for effortless time management with calendar integration and notifications.",
    imgPath: "./Projects images/Next.js/shedule_app.png",
    liveDemo: "https://schedule-app-nh6c.vercel.app/",
    github: "https://github.com/aymantarek16/schedule_App",
    techStack: ["Next.js", "Firebase", "TypeScript", "Tailwind"],
    category: "Productivity",
  },
  {
    id: "web-marketing",
    projectTitle: "Procoor Marketing",
    subTitle: "Professional marketing website for Procoor Company to display services with modern design and smooth interactions.",
    imgPath: "./Projects images/ui/web_site_markiting.png",
    liveDemo: "https://website-marketing-iota.vercel.app/",
    github: "https://github.com/aymantarek16/website_marketing",
    techStack: ["HTML", "CSS", "JavaScript", "Responsive"],
    category: "Marketing",
  },
  {
    id: "225-f",
    projectTitle: "225-F Smokehouse",
    subTitle: "Restaurant website to savor the flavor and elevate meals. Explore the art of smoked delights with beautiful imagery.",
    imgPath: "./Projects images/ui/225-F.png",
    liveDemo: "https://225-f.vercel.app/",
    github: "https://github.com/aymantarek16/225-F",
    techStack: ["HTML", "CSS", "JavaScript", "Animations"],
    category: "Restaurant",
  },
];