export const featuredProjects = [
  {
    id: "careflow-operations-system",
    projectTitle: "CareFlow Operations System",
    subTitle:
      "Premium medical operations system for clinics and healthcare centers. Includes role-based dashboards, appointments, patient records, reception workflow, notifications, and secure data management.",
    imgPath: "./Projects images/careflow.png",
    liveDemo: "https://care-flow-operations-system.vercel.app/login",
    github: "https://github.com/aymantarek16/CareFlow-Operations-System",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase"],
    category: "Healthcare",
  },
  {
  id: "flavre-ecommerce",
  projectTitle: "FLAVRE E-commerce",
  subTitle:
    "Modern restaurant ordering website with a premium Arabic UI, interactive menu browsing, product customization, cart flow, and direct WhatsApp ordering for a fast customer experience.",
  imgPath: "./Projects images/flaver.png",
  liveDemo: "https://flavre.vercel.app/",
  github: "https://github.com/aymantarek16/FLAVRE",
  techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Zustand"],
  category: "Restaurant / E-commerce",
},
{
  id: "royal-barbers-booking-system",
  projectTitle: "Royal Barbers Booking System",
  subTitle:
    "A premium barber shop website with online booking, WhatsApp contact, and a full admin dashboard for managing reservations, customer details, appointment statuses, and business reports.",
  imgPath: "./Projects images/babershop.png",
  liveDemo: "https://fullstack-baber-shop.vercel.app/",
  github: "https://github.com/aymantarek16/fullstack-baber-shop",
  techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase"],
  category: "Booking System",
},
{
  id: "iron-house-gym",
  projectTitle: "Iron House Gym",
  subTitle:
    "Modern gym website designed to showcase fitness services, membership plans, trainers, and direct WhatsApp booking with a strong and professional visual identity.",
  imgPath: "./Projects images/iron-house-gym.png",
  liveDemo: "https://iron-house-gym.vercel.app/",
  github: "https://github.com/aymantarek16?tab=repositories",
  techStack: ["Next.js", "React", "Tailwind", "WhatsApp Booking"],
  category: "Fitness",
},
  {
    id: "virtix-studio",
    projectTitle: "Virtix Studio",
    subTitle: "Premium digital design agency website designed to showcase creative work with stunning animations and modern UX.",
    imgPath: "./Projects images/virtix.png",
    liveDemo: "https://virtix-studio.vercel.app/",
    github: "https://github.com/aymantarek16/virtix-studio",
    techStack: ["Next.js", "Framer Motion", "GSAP", "Tailwind"],
    category: "Agency",
  },
  {
    id: "web-marketing",
    projectTitle: "Procoor Marketing",
    subTitle: "Professional marketing website for Procoor Company to display services with modern design and smooth interactions.",
    imgPath: "./Projects images/web_site_markiting.png",
    liveDemo: "https://website-marketing-iota.vercel.app/",
    github: "https://github.com/aymantarek16/website_marketing",
    techStack: ["HTML", "CSS", "JavaScript"],
    category: "Marketing",
  },
  {
    id: "225-f",
    projectTitle: "225-F Smokehouse",
    subTitle: "Restaurant website to savor the flavor and elevate meals. Explore the art of smoked delights with beautiful imagery.",
    imgPath: "./Projects images/225-F.png",
    liveDemo: "https://225-f.vercel.app/",
    github: "https://github.com/aymantarek16/225-F",
    techStack: ["HTML", "CSS", "JavaScript", "Animations"],
    category: "Restaurant",
  },
];