export const featuredProjects = [
  {
    id: "careflow-operations-system",
    projectTitle: "CareFlow Operations System",
    subTitle:
      "Premium medical operations system for clinics and healthcare centers. Includes role-based dashboards, appointments, patient records, reception workflow, notifications, and secure data management.",
    imgPath: "./Projects images/careflow.png",
    liveDemo: "https://care-flow-operations-system.vercel.app/login",
    github: "https://github.com/aymantarek16/CareFlow-Operations-System",
    techStack: ["React.js", "TypeScript", "Tailwind CSS", "Supabase"],
    category: "Healthcare",
  },
  {
    id: "flexops-erp",
    projectTitle: "FlexOps ERP",
    subTitle:
      "A customizable Arabic ERP dashboard for managing customers, orders, invoices, expenses, reports, and business workflows. Designed as a SaaS-style business management system that can be adapted for clinics, gyms, restaurants, retail stores, and service companies.",
    imgPath: "./Projects images/FlexOps ERP.png",
    liveDemo: "https://flex-ops-erp.vercel.app/",
    github: "https://github.com/aymantarek16/FlexOps-ERP",
    techStack: ["React.js", "TypeScript", "Tailwind CSS", "Zustand"],
    category: "ERP System",
  },
  {
    id: "branded-invoice",
    projectTitle: "Branded Invoice",
    subTitle:
      "Premium multi-account invoice management system for freelancers, agencies, shops, clinics, gyms, restaurants, and small businesses. Includes branded invoices, client and product management, dashboard analytics, multiple invoice themes, PDF/PNG export, print support, and secure user-based data management.",
    imgPath: "./Projects images/Invoice_Portfolio.png",
    liveDemo: "https://branded-invoice.vercel.app/",
    github: "https://github.com/aymantarek16/Branded-Invoice",
    techStack: ["Next.js", "JavaScript", "Tailwind CSS", "Supabase"],
    category: "Business Tools",
  },
  {
    id: "royal-barbers-booking-system",
    projectTitle: "Royal Barbers Booking System",
    subTitle: "A full-stack barber shop booking system with Supabase, online reservations, WhatsApp integration, customer management, appointment status tracking, admin dashboard, and business reports — built as a complete production-ready management solution, not just a landing page.",
    imgPath: "./Projects images/babershop.png",
    liveDemo: "https://fullstack-baber-shop.vercel.app/",
    github: "https://github.com/aymantarek16/fullstack-baber-shop",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase"],
    category: "Booking System",
  },
  
  {
    id: "pulse-space-social-platform",
    projectTitle: "PulseSpace Social Platform",
    subTitle:
      "Modern real-time social platform with authentication, user profiles, posts, reactions, comments, follow system, private messaging, media sharing, notifications, groups, and premium responsive dark UI.",
    imgPath: "./Projects images/pulse-space.png",
    liveDemo: "https://pulse-space-rose.vercel.app/login",
    github: "https://github.com/aymantarek16/Pulse-Space",
    techStack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Firebase Auth",
      "Firestore",
    ],
    category: "Social Platform",
  },
  {
    id: "flavre-ecommerce",
    projectTitle: "FLAVRE E-commerce",
    subTitle:
      "Modern restaurant ordering website with a premium Arabic UI, interactive menu browsing, product customization, cart flow, and direct WhatsApp ordering for a fast customer experience.",
    imgPath: "./Projects images/flaver.png",
    liveDemo: "https://flavre.vercel.app/",
    github: "https://github.com/aymantarek16/FLAVRE",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Zustand"],
    category: "Restaurant / E-commerce",
  },
  {
    id: "iron-house-gym",
    projectTitle: "Iron House Gym",
    subTitle:
      "Modern gym website designed to showcase fitness services, membership plans, trainers, and direct WhatsApp booking with a strong and professional visual identity.",
    imgPath: "./Projects images/iron-house-gym.png",
    liveDemo: "https://iron-house-gym.vercel.app/",
    github: "https://github.com/aymantarek16?tab=repositories",
    techStack: ["Next.js", "React", "Tailwind", "WhatsApp Booking"],
    category: "Fitness",
  },
  {
    id: "virtix-studio",
    projectTitle: "Virtix Studio",
    subTitle: "Premium digital design agency website designed to showcase creative work with stunning animations and modern UX.",
    imgPath: "./Projects images/virtix.png",
    liveDemo: "https://virtix-studio.vercel.app/",
    github: "https://github.com/aymantarek16/virtix-studio",
    techStack: ["Next.js", "Framer Motion", "GSAP", "Tailwind"],
    category: "Agency",
  },
  {
    id: "225-f",
    projectTitle: "225-F Smokehouse",
    subTitle: "Restaurant website to savor the flavor and elevate meals. Explore the art of smoked delights with beautiful imagery.",
    imgPath: "./Projects images/225-F.png",
    liveDemo: "https://225-f.vercel.app/",
    github: "https://github.com/aymantarek16/225-F",
    techStack: ["HTML", "CSS", "JavaScript", "Animations"],
    category: "Restaurant",
  },
  {
    id: "web-marketing",
    projectTitle: "Procoor Marketing",
    subTitle: "Professional marketing website for Procoor Company to display services with modern design and smooth interactions.",
    imgPath: "./Projects images/web_site_markiting.png",
    liveDemo: "https://website-marketing-iota.vercel.app/",
    github: "https://github.com/aymantarek16/website_marketing",
    techStack: ["HTML", "CSS", "JavaScript"],
    category: "Marketing",
  },
];